'''
5- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
Türkçe : Fibonacci dizisindeki her yeni terim, önceki iki terim toplanarak üretilir.
1 ve 2 ile başlayarak ilk 10 terim şöyle olacaktır:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …
Değerleri dört milyonu aşmayan Fibonacci dizisindeki terimleri dikkate alarak, çift sayıların toplamını bulun.
'''

sayi1 = 1
sayi2 = 1
toplam = 0
while True:
    sayi1_eski_degeri = sayi1
    sayi1 = sayi2
    sayi2 = sayi1_eski_degeri + sayi2
    if sayi2 > 4000000:
        break
    if sayi2 % 2 == 0:
        toplam += sayi2

print("Toplam :", toplam)
