'''
1- 1000 den 1000000 a kadar olan palindromik sayıları ekrana yazdıran program
    Palindromik sayı, iki taraftan okunduğu zaman okunuş yönüyle aynı olan sayılara verilen isimdir.
    Örn: 101

2- 1 den 1.000.000.000 a kadar olan asal sayıları bulup ekrana yazdıran program

3- Kendisine parametre olarak bir dikdörtgenin uzun ve kısa kenarın uzunlukları verildiğinde
    aynı anda hem alan hem de çevre değerini hesaplayarak geri döndüren fonksiyonu yazınız.

4- If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
        The sum of these multiples is 23.
    Find the sum of all the multiples of 3 or 5 below 1000.

5- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
Türkçe : Fibonacci dizisindeki her yeni terim, önceki iki terim eklenerek üretilir. 1 ve 2 ile başlayarak ilk 10 terim şöyle olacaktır:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …
Değerleri dört milyonu aşmayan Fibonacci dizisindeki terimleri dikkate alarak, çift sayıların toplamını bulun.

6- 13195 sayısının asal çarpanları 5,7,13 ve 29.
O zaman 600851475143 sayısının en büyük asal çarpanı nedir?

7- By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
What is the 10001st prime number?
'''
